CREATE DATABASE IF NOT EXISTS `shorty`;

USE `shorty`;

CREATE TABLE IF NOT EXISTS urls (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    url TEXT NOT NULL,
    shortcode VARCHAR(6) NOT NULL UNIQUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,
    redirects INTEGER NOT NULL DEFAULT 0
);